# Generated by Django 3.2.14 on 2022-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='months',
            field=models.IntegerField(default=1),
        ),
    ]
