# Generated by Django 3.2.14 on 2022-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='months',
            field=models.IntegerField(),
        ),
    ]
