# Generated by Django 3.2.14 on 2022-07-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='payment_frequency',
            field=models.IntegerField(choices=[(1, 'Mensual'), (12, 'Anual')], default=1),
        ),
    ]
