# Generated by Django 3.2.14 on 2022-07-14 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('clients', '0002_auto_20220714_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=50, verbose_name='Calle y número')),
                ('location', models.CharField(max_length=30, verbose_name='Colonia')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('zip_code', models.CharField(max_length=5, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Sin iniciar'), (1, 'Activo'), (2, 'Suspención temporal'), (3, 'Cancelación')], default=0)),
                ('start_date_operation', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
