# Generated by Django 3.2.14 on 2022-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220714_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='start_date_operation',
            field=models.DateField(verbose_name='Fecha de inicio de operación'),
        ),
    ]
