# Generated by Django 3.2.14 on 2022-07-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_address_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='has_late_payments',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
    ]
