# Generated by Django 3.2.14 on 2022-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20220714_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_last_name',
            field=models.CharField(max_length=20, verbose_name='Apellido materno'),
        ),
    ]
