# Generated by Django 3.2.14 on 2022-07-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20220719_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='belongs_to_partner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_last_name',
            field=models.CharField(max_length=20),
        ),
    ]
