# Generated by Django 3.2.14 on 2022-07-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20220721_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=20, verbose_name='Apellido paterno'),
        ),
        migrations.AlterField(
            model_name='client',
            name='second_last_name',
            field=models.CharField(max_length=20, verbose_name='Apellido materno'),
        ),
    ]
